### ISSUE TITLE
خطا در نصب nginx

### ISSUE THREAD

**Issue by darianBaba** [rahgozar94725/freedom#11]
سلام
هنگام نصب nginx طبق آموزش لینک:
https://github.com/rahgozar94725/freedom/blob/main/nginx/README.md
و پس از اجرای کد:
acme.sh --issue --keylength ec-256 -d sub.test.com -w /opt/freedom/nginx/webroot/
خطای پایین رو دریافت میکنم:

{sub.mydomain.com}:Verify error:{ip}: Fetching http://{sub.mydomain.com}/.well-known/acme-challenge/{یک کد طولانی}: Connection refused

**Comment by darianBaba** [comment]
اشتباه از من بود و متوجهش شدم

**Comment by mehdiabr** [comment]
> اشتباه از من بود و متوجهش شدم

منم این مشکل دارم. چطور حلش کردین؟
