### ISSUE TITLE
کانتینر اجرا نمی شود!

### ISSUE THREAD

**Issue by sahelefarda** [rahgozar94725/freedom#3]
root@srv1675607223:/opt/freedom/Shadowsocks# docker-compose up -d

[+] Running 0/0

[+] Running 0/1  Recreate                                                  0.1s

[+] Running 0/1  Recreate                                                  0.1s

[+] Running 0/1  Recreate                                                  0.3s

[+] Running 0/1  Starting                                                  0.3s

[+] Running 0/1  Starting                                                  0.4s

[+] Running 0/1  Starting                                                  0.5s

[+] Running 0/1  Starting                                                  0.6s

[+] Running 0/1  Starting                                                  0.7s

 ⠿ Container ss  Starting                                                  0.8s

Error response from daemon: failed to create shim task: OCI runtime create faile                    d: runc create failed: unable to start container process: error during container                     init: unable to apply apparmor profile: apparmor failed to apply profile: write                     /proc/self/attr/apparmor/exec: no such file or directory: unknown

root@srv1675607223:/opt/freedom/Shadowsocks#

**Comment by sahelefarda** [comment]
[+] Running 0/1oxy  Starting                                                                   1.0s

 ⠿ Container proxy  Starting                                                                   1.0s

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown

**Comment by sahelefarda** [comment]
هم برای nginx و هم برای shadowsocks کانتینر اجرا نمیشه!
 اولین خطا برای شادوساکس بود دومین خطا برای انجین ایکس

**Comment by hosseinghanbarpor** [comment]
@sahelefarda 
I had this problem. This problem is due to the lack of a Docker related library .
you can run this:

sudo apt-get purge apparmor apparmor-profiles apparmor-utils
sudo apt-get install apparmor-utils apparmor-profiles apparmor-profiles-extra vim-addon-manager
reboot

**Comment by rahgozar94725** [comment]
You haven't created the required files
Read the tutorial carefully
