### ISSUE TITLE
مشکل پنل

### ISSUE THREAD

**Issue by shuvvan** [rahgozar94725/freedom#5]
داداش سلام نمی دونستم چطوری باهات ارتباط بگیرم ولی چند موقع قبل با دوستم واسمون راه اندازی کردی 
ما پنل ثنایی نصب کردیم ولی متاسفانه به مشکل خورده 
ولی دستورات نمایش تنظیمات و اینا هم کار نمی کنن تو پنل

**Comment by Artin-GH** [comment]
منم همون مشکلو با پنل ثنایی دارم

**Comment by Artin-GH** [comment]
احتمالا پنل ثنایی پشتیبانی نمیکنه

**Comment by Artin-GH** [comment]
اگه همینطوره لطفا تو README هم اضافه کنید.

**Comment by mostafa3053** [comment]
دوستان راه حل پیدا نشد ؟

**Comment by mostafa3053** [comment]
این رو بزنید
docker-compose exec xui ./x-ui setting -show
